### ISSUE TITLE
Template import for perf_counter

### ISSUE THREAD

**Issue by Nostro-Dcx** [ansible-collections/community.zabbix#331] opened 2021-02-17 23:35 UTC
##### SUMMARY
When I use zabbix_template for an import I have an Error -32500.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

 community.zabbix.zabbix_template

##### ANSIBLE VERSION
```
ansible 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```
/
```

##### OS / ENVIRONMENT / Zabbix Version
CentOS 8, docker AWX 17 Latest version. Zabbix 5.0.8

##### STEPS TO REPRODUCE
Error -32500: Application error., Cannot read XML: (9) PCDATA invalid Char value 2 [Line: 3035 | Column: 39]
The line is:
                    <key>perf_counter[\2\250]</key>
I tried with 
                    <key>perf_counter[&quot;\2\250&quot;]</key>
But it doesn't work either.
With an older version of the module it worked perfectly and I changed nothing to my System.xml file.

```yaml
- name: "Import Zabbix System Template"
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_password }}"
    template_xml: "{{ lookup('file', 'System.xml') }}"
    state: present
```

##### EXPECTED RESULTS
Template Imported

##### ACTUAL RESULTS

```
{"changed": false, "details": "('Error -32500: Application error., Cannot read XML: (9) PCDATA invalid Char value 2 [Line: 3035 | Column: 39]. while sending {\\.......................................
```

**Comment by sky-joker** [comment] 2021-02-18 13:44
Thank you @Nostro-Dcx for reporting this issue.

In my environment, I succeeded in importing the following XML file.

```xml
<zabbix_export>
    <version>5.0</version>
    <date>2021-02-18T13:30:27Z</date>
    <groups>
        <group>
            <name>Linux servers</name>
        </group>
    </groups>
    <templates>
        <template>
            <template>ExampleTemplate</template>
            <name>ExampleTemplate</name>
            <groups>
                <group>
                    <name>Linux servers</name>
                </group>
            </groups>
            <applications>
                <application>
                    <name>CPU</name>
                </application>
            </applications>
            <items>
                <item>
                    <name>pef01</name>
                    <key>perf_counter[&quot;\2\250&quot;]</key>
                    <value_type>FLOAT</value_type>
                    <units>%</units>
                    <applications>
                        <application>
                            <name>CPU</name>
                        </application>
                    </applications>
                </item>
                <item>
                    <name>CPU</name>
                    <key>proc.cpu.util[,user]</key>
                    <value_type>FLOAT</value_type>
                    <units>%</units>
                    <applications>
                        <application>
                            <name>CPU</name>
                        </application>
                    </applications>
                </item>
            </items>
        </template>
    </templates>
</zabbix_export>
```

**my environment**

* Zabbix Server 5.0.6
* Ansible 2.10.5
* latest Zabbix Collections


Can you please try with the latest [zabbix_template](https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_template.py) whether not the error occur?

**Comment by Nostro-Dcx** [comment] 2021-02-18 22:37
Hello @sky-joker,

First of all, thanks for your answer.

With community.zabbix 1.1.0 I have no problem on importing the file compare to 1.2.0. 
By the way, when I try to import the file by hand it works perfectly too.
Maybe it's due to ansible in 2.9.17 and note in 2.10+. AWX is note up to date in their release.

What do you think?

**Comment by D3DeFi** [comment] 2021-03-13 15:30
@Nostro-Dcx there were some changes to zabbix_template in #226, which was included in 1.2.0 release. Are you able to test this import outside of AWX environment with just plain ansible repo and community.zabbix:1.2.0?

**Comment by DieWeb21** [comment] 2021-03-30 22:13
Hi,

Unfortunately I can't test it. I'll test it with the new 1.3.0 soon.

**Comment by D3DeFi** [comment] 2021-06-29 16:03
As there were no updates in this issue for a longer period of time and we were not able to reproduce the problem, I am closing it.

Please feel free to reopen this if you are still able to reproduce the bug with 1.3.0 or soon incoming 1.4.0

**Closed by D3DeFi** 2021-06-29 16:03 UTC
Labels: bug, module
