### ISSUE TITLE
Local python path passed for remote execution

### ISSUE THREAD

**Issue by adepretis** [ansible-collections/community.zabbix#892] opened 2023-02-05 10:11 UTC
##### SUMMARY

`ansible_python_interpreter` fact set for local API execution interferes with installing user-defined userparameters.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_agent

##### OS / ENVIRONMENT / Zabbix Version

- Target OS: Debian 11

##### STEPS TO REPRODUCE

```yaml
zabbix_agent_userparameters_templates_src: "{{ playbook_dir }}/templates/zabbix/userparameters"
zabbix_agent_userparameters:
  - name: a
  - name: b
  - name: c
```

```yaml
  tasks:
    - name: load | community.zabbix.zabbix_agent
      import_role:
        name: community.zabbix.zabbix_agent
```

##### EXPECTED RESULTS

```yaml
TASK [community.zabbix.zabbix_agent : Installing user-defined userparameters] ***************************************************************************************************************************************************************************************************************************
ok: [my.host] => (item={'name': 'a'})
ok: [my.host] => (item={'name': 'b'})
ok: [my.host] => (item={'name': 'c'})
```

##### ACTUAL RESULTS

```yaml
TASK [community.zabbix.zabbix_agent : Installing user-defined userparameters] ***************************************************************************************************************************************************************************************************************************
ok: [my.host] => (item={'name': 'docker'})
fatal: [my.host]: FAILED! => {}

MSG:

Failed to get information on remote file (/etc/zabbix/zabbix_agentd.d/userparameter_a.conf): /bin/sh: 1: /opt/homebrew/Cellar/ansible/7.1.0/libexec/bin/python3.11: not found
```

##### ANALYSIS

With commit https://github.com/ansible-collections/community.zabbix/commit/ffafe678387f40d1758621744510064aa9ebfa3c the fact `ansible_python_interpreter` is set to the local playbook execution system's Python binary path.

This interferes with

```yaml
  - name: "Installing user-defined userparameters"
    template:
      src: "{{ zabbix_agent_userparameters_templates_src }}/{{ item.name }}.j2"
      dest: "{{ zabbix_agent_include }}/userparameter_{{ item.name }}.conf"
      owner: zabbix
      group: zabbix
      mode: 0644
    notify:
      - restart zabbix-agent
      - restart mac zabbix agent
    become: true
    with_items: "{{ zabbix_agent_userparameters }}"
```

**Comment by BGmot** [comment] 2023-02-05 14:30
Please provide versions for Python, Ansible and this collection.

**Comment by adepretis** [comment] 2023-02-05 16:34
Local OS: Mac OS Ventura on M1
Local Python: 3.11 via Homebrew
Target Python: 3.9.2
Ansible Core: 2.14.1 via Homebrew
community.zabbix: 1.9.1

**Comment by adepretis** [comment] 2023-02-05 16:36
A workaround is btw.:

```yaml
# Inventory hosts file

[all:vars]
ansible_python_interpreter = /usr/bin/python3
```

**Comment by BGmot** [comment] 2023-02-05 18:04
What is your Target OS? I recently fought with the same problem moving our role tests to Ansible 2.14.

**Comment by adepretis** [comment] 2023-02-05 21:21
Target is Debian 11 in that case, but IMO this issue is not related to the target OS.

**Comment by BGmot** [comment] 2023-02-06 00:38
Mentioned by you commit does not affect anything, I get the same error even if I comment this code:
```
#- name: "Set the 'ansible_python_interpreter' to the one we use for running this playbook."
#  set_fact:
#    ansible_python_interpreter: "{{ ansible_playbook_python }}"
#  delegate_to: localhost
#  delegate_facts: true
#  when:
#    - (zabbix_install_pip_packages | bool) or (zabbix_api_create_hostgroup | bool) or (zabbix_api_create_hosts | bool)
```
There is something funky going on with `with_items` in Ansible 2.14. Put only one item in the list and everything will run successfully:
```
zabbix_agent_userparameters:
  - name: a
```
If we have more than one item in the list then the first item is successful and the next one fails.

I have tested this with Ansible 2.11 and it does not have this problem.

So you found a solution for this problem, ok to close the issue?

**Comment by miettal** [comment] 2023-02-09 03:38
I feel something is happening.

After execute zabbix_agent role, 2nd iteration of loop is failed by "interpreter not found problem" in my some hosts.
I think this commit maybe change something global namespace.

**Comment by adepretis** [comment] 2023-02-09 10:27
Yes, it does. But the issues seems to be related to Ansible 2.14 only as @BGmot discovered.

@BGmot if that's nothing community.zabbix can work around by doing things differently than in https://github.com/ansible-collections/community.zabbix/commit/ffafe678387f40d1758621744510064aa9ebfa3c, I guess this can be closed. At least until Ansible 2.14 adoption is significant enough ;-)

**Comment by BGmot** [comment] 2023-02-09 12:06
> Yes, it does. But the issues seems to be related to Ansible 2.14 only as @BGmot discovered.
> 
> @BGmot if that's nothing community.zabbix can work around by doing things differently than in [ffafe67](https://github.com/ansible-collections/community.zabbix/commit/ffafe678387f40d1758621744510064aa9ebfa3c), I guess this can be closed. At least until Ansible 2.14 adoption is reaching significant levels out there ;-)

The problem is that this commit is irrelevant (does not change this behaviour in my tests).

**Comment by BGmot** [comment] 2023-02-09 12:07
> I feel something is happening.
> 
> After execute zabbix_agent role, 2nd iteration of loop is failed by "interpreter not found problem" in my some hosts. I think this commit maybe change something global namespace.

Can you elaborate on "some hosts"? So some hosts succeed and some fail?

**Comment by adepretis** [comment] 2023-02-09 14:14
hm, ok, because 

```
  set_fact:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
```

would/could explain the behaviour/problem IMO ... because in the end, the value of `{{ ansible_playbook_python }}` is stored in the Ansible scripts executed on the remote.

**Comment by BGmot** [comment] 2023-02-09 14:42
It' only for local host (Ansible controller)
```
delegate_to: localhost
```
otherwise playbook would not run at all after this. Just try to comment it out - it does not change anything (if python-netaddr is already installed).

**Comment by miettal** [comment] 2023-02-10 00:06
> So some hosts succeed and some fail?

yes. now I'm investigating the condition.

**Comment by BGmot** [comment] 2023-02-10 04:02
I am stupid. I think I've found what the problem is.
@adepretis, @miettal  please try this branch https://github.com/BGmot/community.zabbix/tree/bgmot_fix_python_interpreter
Or just make local changes according to this commit https://github.com/ansible-collections/community.zabbix/commit/1bbc5eaa3dea6080123a38889506d57d780d4bc5

**Closed** 2023-02-11 13:27 UTC
