### ISSUE TITLE
zabbix_maintenance module Connection object has no attribute 'zbx_api_version' with httpapi connection

### ISSUE THREAD

**Issue by bidetzz** [ansible-collections/community.zabbix#878] opened 2023-01-16 21:50 UTC
##### SUMMARY
When trying to create a maintenance with the zabbix_maintenance module using httpapi for connection, I get this error:
```
      File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_0lzml2eg/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'
```

I'm assuming that the connection using httpapi is done from local to the remote zabbix server. I have nothing ansible related installed on the zabbix host and I believe it should stay that way. I want to make the HTTP calls to the zabbix API from the ansible host.

Feels like I'm missing something regarding the httpapi plugin for zabbix, even if I installed all the dependencies listed in the Requirements part of the README file.

I was using the old method with login_user, login_password and server_url variables and it was working great. Since I saw that it was getting deprecated, I wanted to switch the httpapi but this error is preventing me.

Any help would be appreciated :) 

Thank you!
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_maintenance module

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user1/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/user1/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user1/.local/bin/ansible
  python version = 3.6.9 (default, Nov 25 2022, 14:10:45) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['ansible.posix.profile_tasks', 'timer']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 6.0.12
Running ansible on WSL2

##### STEPS TO REPRODUCE

1. Run ansible-galaxy collection install community.zabbix
2. Create the playbook below
3. Run the playbook with ansible-playbook comand

```yaml
---
- name: Server update
  hosts: localhost
  tasks:
  - name: Create a named maintenance window for host for 90 minutes
    vars:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: 80
      ansible_httpapi_use_ssl: false
      ansible_httpapi_validate_certs: false
      ansible_zabbix_url_path: ""
      ansible_host: server.domain.com
      ansible_user: <user>
      ansible_httpapi_pass: <pass>
    community.zabbix.zabbix_maintenance:
      name: Update of server
      host_name: server
      state: present
      minutes: 90
```

##### EXPECTED RESULTS

I would expect my ansible host to initiate the HTTP connection to my zabbix server specified in the ansible_host variable and create the maintenance.

##### ACTUAL RESULTS

I get an error saying that the Connection object has no attribute 'zbx_api_version'

```paste below
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /home/user1/.ansible/collections/ansible_collections/ansible/netcommon
<server.domain.com> attempting to start connection
<server.domain.com> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /home/user1/.local/bin/ansible-connection
<server.domain.com> local domain socket does not exist, starting it
<server.domain.com> control socket path is /home/user1/.ansible/pc/fba22f8251
<server.domain.com> redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<server.domain.com> Loading collection ansible.netcommon from /home/user1/.ansible/collections/ansible_collections/ansible/netcommon
<server.domain.com> Loading collection community.zabbix from /home/user1/.ansible/collections/ansible_collections/community/zabbix
<server.domain.com> local domain socket listeners started successfully
<server.domain.com> loaded API plugin ansible_collections.community.zabbix.plugins.httpapi.zabbix from path /home/user1/.ansible/collections/ansible_collections/community/zabbix/plugins/httpapi/zabbix.py for platform type community.zabbix.zabbix
<server.domain.com>
<server.domain.com> local domain socket path is /home/user1/.ansible/pc/fba22f8251
<server.domain.com> ESTABLISH LOCAL CONNECTION FOR USER: user1
<server.domain.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc `"&& mkdir "` echo /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc/ansible-tmp-1673965440.2706966-942-58375553109634 `" && echo ansible-tmp-1673965440.2706966-942-58375553109634="` echo /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc/ansible-tmp-1673965440.2706966-942-58375553109634 `" ) && sleep 0'
Using module file /home/user1/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_maintenance.py
<server.domain.com> PUT /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc/tmprfvg2g8j TO /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc/ansible-tmp-1673965440.2706966-942-58375553109634/AnsiballZ_zabbix_maintenance.py
<server.domain.com> EXEC /bin/sh -c 'chmod u+x /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc/ansible-tmp-1673965440.2706966-942-58375553109634/ /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc/ansible-tmp-1673965440.2706966-942-58375553109634/AnsiballZ_zabbix_maintenance.py && sleep 0'
<server.domain.com> EXEC /bin/sh -c '/usr/bin/python3 /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc/ansible-tmp-1673965440.2706966-942-58375553109634/AnsiballZ_zabbix_maintenance.py && sleep 0'
<server.domain.com> EXEC /bin/sh -c 'rm -f -r /home/user1/.ansible/tmp/ansible-local-841z1w3_6zc/ansible-tmp-1673965440.2706966-942-58375553109634/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/user1/.ansible/tmp/ansible-local-22375kvf9j1o5/ansible-tmp-1673919089.6383986-22472-108293076668668/AnsiballZ_zabbix_maintenance.py", line 100, in <module>
    _ansiballz_main()
  File "/home/user1/.ansible/tmp/ansible-local-22375kvf9j1o5/ansible-tmp-1673919089.6383986-22472-108293076668668/AnsiballZ_zabbix_maintenance.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user1/.ansible/tmp/ansible-local-22375kvf9j1o5/ansible-tmp-1673919089.6383986-22472-108293076668668/AnsiballZ_zabbix_maintenance.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_maintenance.py", line 472, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_maintenance.py", line 370, in main
  File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 33, in __init__
  File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
  File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'
fatal: [localhost]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/user1/.ansible/tmp/ansible-local-22375kvf9j1o5/ansible-tmp-1673919089.6383986-22472-108293076668668/AnsiballZ_zabbix_maintenance.py", line 100, in <module>
        _ansiballz_main()
      File "/home/user1/.ansible/tmp/ansible-local-22375kvf9j1o5/ansible-tmp-1673919089.6383986-22472-108293076668668/AnsiballZ_zabbix_maintenance.py", line 92, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/user1/.ansible/tmp/ansible-local-22375kvf9j1o5/ansible-tmp-1673919089.6383986-22472-108293076668668/AnsiballZ_zabbix_maintenance.py", line 41, in invoke_module
        run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_maintenance.py", line 472, in <module>
      File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_maintenance.py", line 370, in main
      File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 33, in __init__
      File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
      File "/tmp/ansible_community.zabbix.zabbix_maintenance_payload_zti0_d9l/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
```

**Comment by BGmot** [comment] 2023-01-17 00:29
Copy-pasted your playbook and ran it without problem.
What version of collection do you use?

**Comment by bidetzz** [comment] 2023-01-17 01:38
I just updated the original post with the full trace-back.
I'm using version 1.5.1. I see that there 1.9.1 avaialble, but I did uninstall it and then installed it again. It's always putting me on 1.5.1.

**Comment by BGmot** [comment] 2023-01-17 02:00
wow... 1.51. was before my time (before I joined this project as contributor).
Try `ansible-galaxy collection install` with `--upgrade` flag, it should upgrade your collection to the latest 1.9.1.

**Comment by bidetzz** [comment] 2023-01-17 02:03
Yeah that felt also weird, when doing ansible-galaxy collection list, it shows me community.zabbix version 1.5.1, but then when I do ansible-galaxy collection install --upgrade community.zabbix,  it says  Skipping 'community.zabbix:1.9.1' as it is already installed..

Not sure if I have something broken on my setup, I did just reinstall ansible from scratch.

**Comment by bidetzz** [comment] 2023-01-17 02:22
I just checked more in details, and the version 1.5.1 was under python3.6/site-packages/ansible_collections,

I do have version 1.9.1 under /home/user1/.ansible/collections/ansible_collections. So I'm running on the latest.

Sorry for the confusion, I deleted the 1.5.1 zabbix collection under python3.6 just to make sure it wasn't causing any problems

**Comment by BGmot** [comment] 2023-01-17 03:04
Please run the playbook with `-vvvv` and provide the output, I wonder if you reach the point with `Web Services:` in the output.

**Comment by Profecy** [comment] 2023-01-17 11:22
I'm running into a similar issue when trying to create a host via the API:

The error was: ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'

The API URL Path has been set to empty since the installation is running in the root directory of the webserver.

ansible_zabbix_url_path: ''

The API URL has been set correctly via zabbix_api_server_url and the API is confirmed to work.

Am I doing something wrong here?

**Comment by Profecy** [comment] 2023-01-17 14:03
I've verified that I'm using Version 1.9.0 in both places, via ansible-galaxy collection list.

Here is the -vvvv Ouptut, usernames and hosnames redacted:

<<zabbixhost>> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4 `"&& mkdir "` echo /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711 `" && echo ansible-tmp-1673963874.8389425-1118022-58483029106711="` echo /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711 `" ) && sleep 0'
Using module file /home/*******/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<<zabbixhost>> PUT /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/tmp5l_zleak TO /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py
<<zabbixhost>> EXEC /bin/sh -c 'chmod u+x /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/ /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py && sleep 0'
<<zabbixhost>> EXEC /bin/sh -c '/usr/bin/python3.9 /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py && sleep 0'
<<zabbixhost>> EXEC /bin/sh -c 'rm -f -r /home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py", line 107, in <module>
    _ansiballz_main()
  File "/home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 1289, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 1083, in main
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 33, in __init__
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'
fatal: [<hostname> -> <zabbixhost>]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/*******/.ansible/tmp/ansible-local-1117472a5s1xux4/ansible-tmp-1673963874.8389425-1118022-58483029106711/AnsiballZ_zabbix_host.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1289, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1083, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 33, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_5j5tlh6q/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by Profecy** [comment] 2023-01-17 16:27
This ist the output of ansible --version

ansible [core 2.14.1]
  config file = /home/*********/das-boot/ansible.cfg
  configured module search path = ['/home/*********/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/*********/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/*********/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/*********/.local/bin/ansible
  python version = 3.9.7 (default, Sep 21 2021, 00:13:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

**Comment by BGmot** [comment] 2023-01-17 16:38
I installed the same version as @bidetzz :
```
root@45d7c4774393:/# ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.9 (default, Nov 25 2022, 14:10:45) [GCC 8.4.0]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
/usr/local/lib/python3.6/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.exceptions import InvalidSignature
ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov 25 2022, 14:10:45) [GCC 8.4.0]
  jinja version = 3.0.3
  libyaml = True
```
My playbook:
```
root@45d7c4774393:/# cat test_maintenance_httpapi.yml 
---
- name: Server update
  hosts: localhost
  tasks:
  - name: Create a named maintenance window for host for 90 minutes
    vars:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: 8080
      ansible_httpapi_use_ssl: false
      ansible_httpapi_validate_certs: false
      ansible_zabbix_url_path: "/"
      ansible_host: 192.168.148.200
      ansible_user: Admin
      ansible_httpapi_pass: zabbix
    community.zabbix.zabbix_maintenance:
      name: Update of server
      host_name: Zabbix server
      state: present
      minutes: 90
```
Playbook run:
```
root@45d7c4774393:/# ansible-playbook test_maintenance_httpapi.yml
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.9 (default, Nov 25 2022, 14:10:45) [GCC 8.4.0]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
/usr/local/lib/python3.6/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.exceptions import InvalidSignature

PLAY [Server update] *****************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create a named maintenance window for host for 90 minutes] *********************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

I can't fix anything unless I can reproduce the issue, really need to reproduce it -\

**Comment by BGmot** [comment] 2023-01-17 16:54
Do you guys specify any inventory when you run your playbook?
What's in your ansible.cfg globally and on playbook level (if any)?

**Comment by Profecy** [comment] 2023-01-17 17:03
Well, I'm using a role with several tasks in it and run it against a single host that has this role attached, nothing fancy.
The funny t hing is that it used to work some time ago.
I kind of "inherited" said role from another admin and I myself am new to ansible.

In the yaml for the task it says this:

```
- name: Install Zabbix Agent
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_agent
```

**Comment by bidetzz** [comment] 2023-01-17 19:42
I removed the config file and also removed the inventory file to test with only the IP directly (like you did in your playbook that was working) and I get the same error..

**Comment by bidetzz** [comment] 2023-01-17 21:00
So I just tested with a completelty new machine on Ubuntu 20.04 fresh install.

1. apt-get update
2. python3 -m pip install --user ansible
3. ansible --version:
```
ansible [core 2.13.7]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```
4. Copied my playbook to that host
5. Ran the playbook without an inventory or config file

And I get the same error again.
Could you try on a fresh setup @BGmot ?

**Comment by BGmot** [comment] 2023-01-17 21:24
@bidetzz I literally created a docker container (it's impossible to be more fresh), installed collection and tried the same playbook. Btw Ubuntu 20.04 has slightly outdated python and ansible (not that it matters)...

You did not install zabbix collection? Or just did not post this step?
Are you open to modify some code in collection to see where exactly the error happens (traceback is vague because of this multiple inheritance and handling exceptions on multiple levels -\

**Comment by BGmot** [comment] 2023-01-17 21:26
Please provide `ansible-galaxy collection list | egrep "zabb|netcomm"` I need to know version of `ansible.netcommon` collection, we heavily depend on it.

**Comment by BGmot** [comment] 2023-01-18 00:11
Though tried with ancient ansible.netcommon 2.5.0, still works without problem, really puzzled...

**Comment by BGmot** [comment] 2023-01-18 14:23
Fresh Ubuntu 20.04.
1. apt-get update
2. apt-get upgrade
3. apt install python3 python3-pip
4. python3 -m pip install --user ansible
```
root@c3be8e3552fe:/# ansible --version
ansible [core 2.13.7]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```
5. Ansible install comes with these collections
```
root@c3be8e3552fe:/# ansible-galaxy collection list | egrep "netcomm|zabb"
ansible.netcommon             3.1.3
community.zabbix              1.9.0
```
6. Playbook
```
---
- name: Server update
  hosts: localhost
  tasks:
  - name: Create a named maintenance window for host for 90 minutes
    vars:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: 8080
      ansible_httpapi_use_ssl: false
      ansible_httpapi_validate_certs: false
      ansible_zabbix_url_path: "/"
      ansible_host: 192.168.148.200
      ansible_user: Admin
      ansible_httpapi_pass: zabbix
    community.zabbix.zabbix_maintenance:
      name: Update of server
      host_name: Zabbix server
      state: present
      minutes: 90
```
7. Playbook run
```
root@c3be8e3552fe:/# ansible-playbook test_maintenance_httpapi.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Server update] *****************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create a named maintenance window for host for 90 minutes] *********************************************************************************************************************************************************************************************************
[WARNING]: Option "server_url" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "login_user" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "login_password" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "timeout" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "validate_certs" is deprecated with the move to httpapi connection and will be removed in the next release
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
8. Upgrade collections `ansible-galaxy list | egrep "netcomm|zabb"`
9. Now having these versions:
```
root@c3be8e3552fe:/# ansible-galaxy collection list | egrep "netcomm|zabb"
ansible.netcommon    4.1.0
community.zabbix     1.9.1
ansible.netcommon             3.1.3
community.zabbix              1.9.0
```
10. Playbook run:
```
root@c3be8e3552fe:/# ansible-playbook test_maintenance_httpapi.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Server update] *****************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create a named maintenance window for host for 90 minutes] *********************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by bidetzz** [comment] 2023-01-18 15:17
@BGmot Yes sorry I forgot to add the step but I did indeed install the zabbix collection.

Checking for the netcommon version with your command: 
```
 ansible-galaxy collection list | egrep "netcomm|zabb"
ansible.netcommon             3.1.3
community.zabbix              1.9.0
ansible.netcommon    4.1.0
community.zabbix     1.9.1

```

So we have exactly the same setup and mine is still having that same error. Could it be something related to the zabbix server itself ? Trying to find the thing that is different between both of our setup... I am on 6.0.12.

I'm also wondering why you are getting the warnings for deprecated variables with the old connection method ? Should you only get these if you're actually using the variables? On my side I don't get the warnings if I don't use them.

**Comment by BGmot** [comment] 2023-01-18 15:25
I am testing with 6.0.8 but you do not get to actually make an API call to Zabbix, the exception happens earlier (you can confirm that with tcpdump).
There was a problem with warnings in 1.9.0 that I fixed in 1.9.1.

**Comment by bidetzz** [comment] 2023-01-18 15:29
Got it, and to answer your question earlier, yes I can change some code in the collection on my fresh setup.

**Comment by BGmot** [comment] 2023-01-18 15:29
What is your "Ubuntu 20.04"? A VM? a container? You mentioned something about WSL...

**Comment by bidetzz** [comment] 2023-01-18 15:31
So originally I'm developping with WSL, but the fresh Ubuntu 20.04 is a VM, I did try also with a container and got the same error (running on alpine and installing ansible/python3/zabbix collection)

**Comment by BGmot** [comment] 2023-01-18 15:39
Right before line https://github.com/ansible-collections/community.zabbix/blob/main/plugins/httpapi/zabbix.py#L106 put
```
        raise Exception(type(self))
```
Run your playbook, traceback should be the same, post what you get after `ansible.module_utils.connection.ConnectionError:`

Then delete what you added and add following right after the same line
```
            raise Exception(type(self.connection))
```
Run your playbook,  traceback should be the same, post what you get after `ansible.module_utils.connection.ConnectionError:`

If you prefer we can chat here https://matrix.to/#/#community-zabbix_community:gitter.im

**Comment by bidetzz** [comment] 2023-01-18 16:38
After back and forth debug with @BGmot, we found that the problem was related to the use of HTTP instead of HTTPS. My zabbix server has HTTP disabled since we are using only HTTPS. In the playbook, I need to set these variables instead:
```
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
```
Thank you again for your help @BGmot, I would suggest adding info/examples regarding zabbix servers with HTTPS only.

**Comment by BGmot** [comment] 2023-01-18 16:44
Small correction: HTTP is not closed (in this case we would have meaningful error message), it is redirecting to HTTPS.
I will add better error reporting to the code.

**Comment by BGmot** [comment] 2023-01-22 16:42
No response. Closing as resolved.

**Closed by BGmot** 2023-01-22 16:42 UTC
