### ISSUE TITLE
Zabbix actions - Use scripts - Zabbix 6.0

### ISSUE THREAD

**Issue by feelan03** [ansible-collections/community.zabbix#688] opened 2022-05-09 10:26 UTC
Good afternoon. In zabbix 6.0 it is not possible to use custom_commands as it was possible before. Now, in order to use a custom script in an Action, you first need to add it to Administration > Scripts. Set scope: Action operation. Then in Actions select the desired script.

**Comment by BGmot** [comment] 2022-05-09 11:26
Good afternoon. It is not a problem of this Ansible collection. It is a change to Zabbix 6.0 comparing to 5.0. Module that will let you to create Scripts is coming soon https://github.com/ansible-collections/community.zabbix/issues/634

**Comment by D3DeFi** [comment] 2022-05-10 07:34
Hi, in addition to what @BGmot has stated I am closing this issue as a duplicate of #634. Feel free to comment there if you have any additional insight that may help with module development.

**Closed by D3DeFi** 2022-05-10 07:34 UTC
