### ISSUE TITLE
Zabbix Agent - Disable repo configuration

### ISSUE THREAD

**Issue by lumarel** [ansible-collections/community.zabbix#981] opened 2023-05-08 09:32 UTC
##### SUMMARY
Since the version 2.0.0 I don't see an option to disable the repo configuration anymore.

We have local mirrors of the Zabbix repos (central package management), and these are preconfigured before the run of the Zabbix Agent role. Is it possible to readd an option to disable the automatic repo configuration?

Best case it is not breaking the previous property, but also fine if it is. The previously used option was:

```yaml
zabbix_repo: other
```

(this also means the used Agent version is just the latest in the repo, hence no need to provide a explicit version, previously we specified just the major version, but this is not working anymore now)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_agent

**Comment by oebeledrijfhout** [comment] 2023-05-08 14:19
This is a major regression. In most corporate environments centralized package management is the norm. Even overwriting the `zabbix_repo_yum` var doesn't work because of the hardcoded `disablerepo: epel` in the agent/sender/get install tasks.

**Comment by pyrodie18** [comment] 2023-05-09 03:59
> This is a major regression. In most corporate environments centralized package management is the norm. Even overwriting the `zabbix_repo_yum` var doesn't work because of the hardcoded `disablerepo: epel` in the agent/sender/get install tasks.

Overwriting the `zabbix_repo_yum` was going to be my suggestion.  If that's done then what does the `disablerepo: epel` prevent you from doing?

**Comment by pyrodie18** [comment] 2023-05-09 04:03
> (this also means the used Agent version is just the latest in the repo, hence no need to provide a explicit version, previously we specified just the major version, but this is not working anymore now)
> 

Not sure I'm following what you mean here.  `zabbix_agent_version` is available and will install the version it's set to.

**Comment by pyrodie18** [comment] 2023-05-10 01:16
> We're running into a similar issue. since we don't have any repo named "epel". the tasks simply fails because there is no such repo found.

@plicon , Ansible should handle `disablerepo` gracefully even if epel doesn't exist.  I just ran a test (see below) and it worked fine.  If you're getting an error here, go ahead and post the printout.

```
TASK [community.zabbix.zabbix_server : RedHat | Installing zabbix-server-pgsql] ***
task path: /root/devel/collections/ansible_collections/community/zabbix/roles/zabbix_server/tasks/RedHat.yml:49
<zabbix-server-> ESTABLISH DOCKER CONNECTION FOR USER: root
<zabbix-server-> EXEC ['/usr/bin/docker', b'exec', b'-i', 'zabbix-server-', '/bin/sh', '-c', "/bin/sh -c 'echo ~ && sleep 0'"]
<zabbix-server-> EXEC ['/usr/bin/docker', b'exec', b'-i', 'zabbix-server-', '/bin/sh', '-c', '/bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1683680948.0374892-3594054-154541575807353 `" && echo ansible-tmp-1683680948.0374892-3594054-154541575807353="` echo /root/.ansible/tmp/ansible-tmp-1683680948.0374892-3594054-154541575807353 `" ) && sleep 0\'']
Using module file /usr/local/lib/python3.9/site-packages/ansible/modules/dnf.py
<zabbix-server-> PUT /root/.ansible/tmp/ansible-local-3592765rgpf1hyb/tmpsk8n9bwg TO /root/.ansible/tmp/ansible-tmp-1683680948.0374892-3594054-154541575807353/AnsiballZ_dnf.py
<zabbix-server-> EXEC ['/usr/bin/docker', b'exec', b'-i', 'zabbix-server-', '/bin/sh', '-c', "/bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1683680948.0374892-3594054-154541575807353/ /root/.ansible/tmp/ansible-tmp-1683680948.0374892-3594054-154541575807353/AnsiballZ_dnf.py && sleep 0'"]
<zabbix-server-> EXEC ['/usr/bin/docker', b'exec', b'-i', 'zabbix-server-', '/bin/sh', '-c', '/bin/sh -c \'sudo -H -S -n  -u root /bin/sh -c \'"\'"\'echo BECOME-SUCCESS-lulsoxgxbdgaxapyimydndskzetbtvoo ; http_proxy=\'"\'"\'"\'"\'"\'"\'"\'"\'\'"\'"\'"\'"\'"\'"\'"\'"\' https_proxy=\'"\'"\'"\'"\'"\'"\'"\'"\'\'"\'"\'"\'"\'"\'"\'"\'"\' /usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1683680948.0374892-3594054-154541575807353/AnsiballZ_dnf.py\'"\'"\' && sleep 0\'']
<zabbix-server-> EXEC ['/usr/bin/docker', b'exec', b'-i', 'zabbix-server-', '/bin/sh', '-c', "/bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1683680948.0374892-3594054-154541575807353/ > /dev/null 2>&1 && sleep 0'"]
changed: [zabbix-server-] => {
    "attempts": 1,
    "changed": true,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "allowerasing": false,
            "autoremove": false,
            "bugfix": false,
            "cacheonly": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [
                "test_repo" 
            ],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "zabbix-server-pgsql-6.4.*"
            ],
            "nobest": false,
            "pkg": "zabbix-server-pgsql-6.4.*",
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "update_only": false,
            "validate_certs": true
        }
    },
    "msg": "",
    "rc": 0,
    "results": [
        "Installed: fping-4.2-2.el8.x86_64",
        "Installed: libevent-2.1.8-5.el8.x86_64",
        "Installed: libssh-config-0.9.6-3.el8.noarch",
        "Installed: net-snmp-libs-1:5.8-25.el8_7.1.x86_64",
        "Installed: libtool-ltdl-2.4.6-25.el8.x86_64",
        "Installed: unixODBC-2.3.7-1.el8.x86_64",
        "Installed: libssh-0.9.6-3.el8.x86_64",
        "Installed: libpq-13.5-1.el8.x86_64",
        "Installed: zabbix-server-pgsql-6.4.2-release1.el8.x86_64",
        "Installed: OpenIPMI-libs-2.0.31-3.el8.x86_64"
    ]
}
```

**Comment by lumarel** [comment] 2023-05-10 07:06
Just to make sure, I understand now how I should do it for the Redhat family based systems, with:
`zabbix_repo_yum: ''`

But what about Debian family based systems? Don't see an option there.

**Comment by pyrodie18** [comment] 2023-05-10 22:27
hhmmm...now that you mention Debian, I just realized there's no way to override what repos get added on Debian....let me ponder that one for a minute.

**Comment by oebeledrijfhout** [comment] 2023-05-10 23:10
> If you're getting an error here, go ahead and post the printout.

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ansible.legacy.yum_payload_kqgsrF/ansible_ansible.legacy.yum_payload.zip/ansible/modules/yum.py", line 570, in yum_base
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 240, in disableRepo
    thisrepo = self.getRepo(repoid)
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 205, in getRepo
    'Error getting repository data for %s, repository not found' % (repoid)
fatal: [xxxxxxxx]: FAILED! => changed=false
  attempts: 3
  invocation:
    module_args:
      allow_downgrade: false
      autoremove: false
      bugfix: false
      cacheonly: false
      conf_file: null
      disable_excludes: null
      disable_gpg_check: false
      disable_plugin: []
      disablerepo:
      - epel
      download_dir: null
      download_only: false
      enable_plugin: []
      enablerepo: []
      exclude: []
      install_repoquery: true
      install_weak_deps: true
      installroot: /
      list: null
      lock_timeout: 30
      name:
      - zabbix-agent2-6.0.*
      pkg:
      - zabbix-agent2-6.0.*
      releasever: null
      security: false
      skip_broken: false
      sslverify: true
      state: present
      update_cache: false
      update_only: false
      use_backend: auto
      validate_certs: true
  msg: 'Failure talking to yum: Error getting repository data for epel, repository not found'
  ```

**Comment by pyrodie18** [comment] 2023-05-15 01:36
hhmmm....I wonder why you're erroring out, and I'm not.

**Comment by oebeledrijfhout** [comment] 2023-05-15 20:58
Thats kinda obvious: you're running a different OS, EL8. So the module uses dnf. My output is from CentOS 7, so the module uses yum. 
Yum on CentOS7, without epel:
```
[root@628c78b5c213 /]# yum update --disablerepo=epel
Loaded plugins: fastestmirror, ovl


Error getting repository data for epel, repository not found
```

dnf on Alma8, without epel:
```
[root@8a716a583d28 /]# dnf update --disablerepo=epel
No repository match: epel
AlmaLinux 8 - BaseOS                                                                    8.5 MB/s | 6.3 MB     00:00
AlmaLinux 8 - AppStream                                                                  10 MB/s |  12 MB     00:01
AlmaLinux 8 - Extras                                                                     42 kB/s |  19 kB     00:00
Dependencies resolved.
<...>
```

**Comment by pyrodie18** [comment] 2023-05-22 02:14
@D3DeFi , question for you.  I'm doing a fix for this but when I was doing it, realized that the web role in both the Apache and Nginx tasks still include the original disable and enable repos that used to be there pre-2.0.  If I remove them and standardize them with the rest of the roles, do you think that would be considered a breaking change?  The enable repo is being removed completely and I plan on replacing the disablerepo with a variable that defaults to epel but can be omited if left blank to fix this ticket.

**Comment by pyrodie18** [comment] 2023-05-24 12:25
Technically I don't think this is a breaking change since it will still default to disable epel.  It'll be a bug fix since you'll be able to override it.  Hope to get this pushed up tonight.

**Closed** 2023-05-27 00:47 UTC

**Comment by lumarel** [comment] 2023-05-27 12:48
> hhmmm...now that you mention Debian, I just realized there's no way to override what repos get added on Debian....let me ponder that one for a minute.

@pyrodie18 I don't see a fix for the Debian family path 🤔
Or did you find a was that is possible with the current implementation?

**Comment by pyrodie18** [comment] 2023-05-27 13:27
> > hhmmm...now that you mention Debian, I just realized there's no way to override what repos get added on Debian....let me ponder that one for a minute.
> 
> @pyrodie18 I don't see a fix for the Debian family path 🤔 Or did you find a way that is possible with the current implementation?

Actually forgot about the 2nd issue since it got buried a little bit in the ticket.  See #1001

**Comment by lumarel** [comment] 2023-05-27 13:46
Ah thanks 🙂
